language: python
python:
- 3.7.4
dist: xenial
services:
- xvfb
install:
- pip install -r requirements.txt
script:
- python manage.py collectstatic
deploy:
  provider: heroku
  app: ms-django-rest-tutorial
  on: MS_ICTRAINING-708_Django-REST-Tutorial
  api_key:
    secure: BYNXTxKsd7xvafzGVHojeczfidXsgAaCV8QmzD+4FPDhWupW+g8c+o25SXymUqo+GhDZ23WJWljwc5IzcDB4MIcBnxU75rLbFrgLqcyS9EY9pT4ugGVciJWdOmQ4qh35TPYEvyq8vrA7uRBEE6zTJDM4wJ/rzGDKG2tCD3g8z7DzfxP9atTKdRGk4vld77kF4Nzvn+aHdofnuG0jbaWm3u3hrVZusZCK3mjh+pHtFd3dj7BLbAyiO2p7VTa8Fwa2uA2ulRni9z1lfI4xZjnXWNd8y5Mht5z1W1C9q3gE1XUvh5TqwkC44jK/jhQBX3OX1HA8yt1TvAmT3r7nw2SfMNlzDyGTbelMxyZ3MwJi5KrOA/FD9B/ya0vbEBih35er+GmKtB9IFUpGpACH9dQ/A3v2t0oBvS378zZeOMkC37EVugGcQe8IhhyG3h1123r8deULIz+vEJFRgkBYkxoHqKiD2ZPwN3JhUVsmck6v+S3GESsP4zA27HRVSdnycIbP/Y8dIoJKfJ0wM4Oh2sw1GXPEIYlqIUcEgIapaOF27z1mGBMtQLxmCLIhbMXIwA09Nkrz2eQG0fTdwEuCOrqbbaDz0IWbrZg4iofqPp53NMrWGo5Trd3fvMK7aY5eXjstBehFP2b8iXZT0EQGynguvGczQT7Ez8lGpbcn/ciW1FI=
