language: python
python:
- 3.7.4
dist: xenial
services:
- xvfb
install:
- pip install -r requirements.txt
script:
- python manage.py collectstatic
deploy:
  provider: heroku
  app: ms-django-rest-tutorial
  on:  MS_ICTRAINING-708_Django-REST-Tutorial
  api_key:
    secure: bnuZfWGUFntoRAaLg8HR6RIfIYsl6Mv4o9vct/JCDY25gwKIg71g7JmbaSTfRIODQfQHy20TfL7RCAPxfORyCih9sVURhAFK8SovP5j1nNfu2oWCwTGWKQj6jcgLZqDwkMS9nsMb5JWPlkqy4Bt7TnN3OF3oHULCD7Bo3238zyYUnORo0Q2MrSXXEu04Zu0CVeAkviNqpJQZ8raQ3LbPNXXHpKVnZ78OyCOscWddhqYrAYiLuFY8iU1VCY1jnJahH+dQoPVySq3B7Nwa+QB8oHgRJVsGO8EU1TOHDmGxcTKeWDNLILd14TuWyPQDztx+nIfWA2s+KoiVZ2CyQ8R/Wsn6up/HcoLsmZYn59wXllVwrMpQsgoS91T62saiqi1Q+EcUsFlfkzVIWzNi4l8atIyppBG5RgeBorB3KUohQk0yYl8KL2zZHQuBBwQcsHBZIv2qtKSmeaFGgXSdFSO2A+JllAQbaysZpC4p6pJSOnQ8xmxR02iNETwYzveoGodvdjlznTLC3UTLH3QLy6ABLC15b3BZshv30ePPHvZdqCPD7bMEVRC2BdraHizoKWAX12XCR16QEyMdPZke/Zxh8wx9Xwiz+J9NK1Jg/YQ6MRzJnk8QR/Y7NWT+LTxBiizbIdumIK161YDzBhqsJ436NzUxiEZj8KLohcCZpqp1/VI=